(part "OP213FSZ"
    (packageRef "SOIC127P600X175-8N")
    (interface
        (port "1" (symbPinId 1) (portName "OUT_A") (portType INOUT))
        (port "2" (symbPinId 2) (portName "-IN_A") (portType INOUT))
        (port "3" (symbPinId 3) (portName "+IN_A") (portType INOUT))
        (port "4" (symbPinId 4) (portName "V-") (portType INOUT))
        (port "5" (symbPinId 5) (portName "+IN_B") (portType INOUT))
        (port "6" (symbPinId 6) (portName "-IN_B") (portType INOUT))
        (port "7" (symbPinId 7) (portName "OUT_B") (portType INOUT))
        (port "8" (symbPinId 8) (portName "V+") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "584-OP213FSZ")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Analog-Devices/OP213FSZ?qs=WIvQP4zGanht4Vig9f9CDQ%3D%3D")
    (property "Manufacturer_Name" "Analog Devices")
    (property "Manufacturer_Part_Number" "OP213FSZ")
    (property "Description" "OP213FSZ")
    (property "Datasheet_Link" "https://datasheet.datasheetarchive.com/originals/distributors/SFDatasheet-4/sf-00085565.pdf")
    (property "symbolName1" "OP213FSZ")
)
